// Generated by scripts/generate-author-profiles.ts. Do not edit.
export const authorProfilesMap: Readonly<Record<string, string>> = {
  "4rcadia": "Arcadi4",
  "BFladderbean": "BFladderbeanawa",
  "Molforte": "Molforte",
  "Petris": "Petris",
  "Ryan100c": "hotpad100c",
  "Twisuki": "Twisuki",
  "tanh_Heng": "tanhHeng",
  "xhbsh": "SDU-Little-River"
}

export function getAuthorProfileHandle(peopleKey: string): string | null {
  return authorProfilesMap[peopleKey] ?? null
}
