allowBuilds:
  '@ladybugdb/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  gitnexus: true
  onnxruntime-node: true
  prisma: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-c-sharp: true
  tree-sitter-cpp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-php: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
minimumReleaseAgeExclude:
  - '@next/env@16.3.0-canary.83'
  - '@next/swc-darwin-arm64@16.3.0-canary.83'
  - '@next/swc-darwin-x64@16.3.0-canary.83'
  - '@next/swc-linux-arm64-gnu@16.3.0-canary.83'
  - '@next/swc-linux-arm64-musl@16.3.0-canary.83'
  - '@next/swc-linux-x64-gnu@16.3.0-canary.83'
  - '@next/swc-linux-x64-musl@16.3.0-canary.83'
  - '@next/swc-win32-arm64-msvc@16.3.0-canary.83'
  - '@next/swc-win32-x64-msvc@16.3.0-canary.83'
  - next@16.3.0-canary.83
